"""Added name of the user

Revision ID: ad2c6e3d5bc6
Revises: 74f3224bc277
Create Date: 2023-11-20 03:14:33.399666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad2c6e3d5bc6'
down_revision: Union[str, None] = '74f3224bc277'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
