"""Update user model field name to created_at

Revision ID: b1de4699fb96
Revises: 10aadb248510
Create Date: 2023-11-24 02:28:43.879699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1de4699fb96'
down_revision: Union[str, None] = '10aadb248510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('user', 'last_update')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_update', sa.DATETIME(), nullable=True))
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
